# Generated by Django 3.1.4 on 2020-12-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstats',
            name='type',
        ),
        migrations.AddField(
            model_name='linkstats',
            name='visit_count',
            field=models.IntegerField(null=True),
        ),
    ]
