# Generated by Django 3.1.4 on 2020-12-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201226_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkstats',
            old_name='visit_count',
            new_name='visitCount',
        ),
    ]
